//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.PatientAdmission = new HashSet<PatientAdmission>();
            this.Personnel = new HashSet<Personnel>();
        }
    
        public int ID { get; set; }
        public string Department { get; set; }
    
        public virtual ICollection<PatientAdmission> PatientAdmission { get; set; }
        public virtual ICollection<Personnel> Personnel { get; set; }
    }
}
