//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.PatientAdmissions = new HashSet<PatientAdmission>();
            this.Personnels = new HashSet<Personnel>();
        }
    
        public int ID { get; set; }
        public string Department1 { get; set; }
    
        public virtual ICollection<PatientAdmission> PatientAdmissions { get; set; }
        public virtual ICollection<Personnel> Personnels { get; set; }
    }
}
