//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionaries
    {
        public int ID { get; set; }
        public string Tag { get; set; }
        public int Language_ID { get; set; }
        public string Text { get; set; }
        public string Type { get; set; }
    
        public virtual SupportedLanguages SupportedLanguages { get; set; }
    }
}
