//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAdmission
    {
        public int ID { get; set; }
        public int Patient_ID { get; set; }
        public int Department_ID { get; set; }
        public System.DateTime Date_From { get; set; }
        public Nullable<System.DateTime> Date_Till { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
