//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public Patients()
        {
            this.PatientAdmission = new HashSet<PatientAdmission>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string SocialNr { get; set; }
    
        public virtual ICollection<PatientAdmission> PatientAdmission { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
