//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public Personnel()
        {
            this.Tasks = new HashSet<Tasks>();
            this.Tasks1 = new HashSet<Tasks>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string SocialNr { get; set; }
        public int Position_ID { get; set; }
        public int Department_ID { get; set; }
        public string Password { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
        public virtual ICollection<Tasks> Tasks1 { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
