//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID { get; set; }
        public int Task_ID { get; set; }
        public int Status_ID { get; set; }
        public System.DateTime TimeAdded { get; set; }
        public string Attachment { get; set; }
        public string Comment { get; set; }
    
        public virtual Statuses Statuses { get; set; }
    }
}
