//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportedLanguage
    {
        public SupportedLanguage()
        {
            this.Dictionaries = new HashSet<Dictionary>();
        }
    
        public int ID { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<Dictionary> Dictionaries { get; set; }
    }
}
