//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public int Type_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Priority_ID { get; set; }
        public string Instructions { get; set; }
        public int Status_ID { get; set; }
        public int Creator_ID { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<int> Responsible_ID { get; set; }
        public System.DateTime TimeUpdated { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual PriorityType PriorityType { get; set; }
        public virtual Status Status { get; set; }
        public virtual TaskType TaskType { get; set; }
    }
}
